name: statussaver
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  video_player: ^2.7.2
  video_thumbnail: ^0.5.3
  chewie: ^1.7.1
  share_plus: ^7.2.1
  provider: ^6.0.5
  get: ^4.6.5
  url_launcher: ^6.1.12
  intl: ^0.18.1
  iconsax: ^0.0.8
  flutter_staggered_grid_view: ^0.7.0
  zoom_pinch_overlay: ^1.4.1+3
  firebase_core: ^2.20.0
  google_mobile_ads: ^3.1.0
  firebase_storage: ^11.4.0
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  #  Assets we are using in our app
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/

  #  Fonts we are using in our app
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
